module.exports = {

  'ALL_GENRES': ['Crime', 'Drama', 'Comedy', 'Action', 'Thriller', 'Adventure', 'Science Fiction', 'Animation',
  'Family', 'Romance', 'Mystery', 'Music', 'Horror', 'Fantasy', 'Documentary', 'War', 'Western', 'History',
  'TV Movie', 'Foreign'],

  'TOP_10': {
    'Comedy': '[{"title":"Dilwale Dulhania Le Jayenge","rating":9.1,"vote_count":661,"genre":"Comedy","$$hashKey":"object:43"},{"title":"Cosy Dens","rating":8.6,"vote_count":23,"genre":"Comedy","$$hashKey":"object:44"},{"title":"Too Many Cooks","rating":8.5,"vote_count":24,"genre":"Comedy","$$hashKey":"object:45"},{"title":"Bill Hicks: Revelations","rating":8.5,"vote_count":21,"genre":"Comedy","$$hashKey":"object:46"},{"title":"Bo Burnham: Make Happy","rating":8.4,"vote_count":56,"genre":"Comedy","$$hashKey":"object:47"},{"title":"Life Is Beautiful","rating":8.3,"vote_count":3643,"genre":"Comedy","$$hashKey":"object:48"},{"title":"In a Heartbeat","rating":8.3,"vote_count":146,"genre":"Comedy","$$hashKey":"object:49"},{"title":"The Present","rating":8.3,"vote_count":52,"genre":"Comedy","$$hashKey":"object:50"},{"title":"Toto, Peppino, and the Hussy","rating":8.3,"vote_count":48,"genre":"Comedy","$$hashKey":"object:51"},{"title":"Louis C.K.: Chewed Up","rating":8.3,"vote_count":46,"genre":"Comedy","$$hashKey":"object:52"}]',
    'Crime': '[{"title":"The Shawshank Redemption","rating":8.5,"vote_count":8358,"genre":"Crime","$$hashKey":"object:83"},{"title":"The Godfather","rating":8.5,"vote_count":6024,"genre":"Crime","$$hashKey":"object:84"},{"title":"Dear Zachary: A Letter to a Son About His Father","rating":8.4,"vote_count":146,"genre":"Crime","$$hashKey":"object:85"},{"title":"A Brighter Summer Day","rating":8.4,"vote_count":45,"genre":"Crime","$$hashKey":"object:86"},{"title":"Pixote","rating":8.4,"vote_count":24,"genre":"Crime","$$hashKey":"object:87"},{"title":"The Dark Knight","rating":8.3,"vote_count":12269,"genre":"Crime","$$hashKey":"object:88"},{"title":"Pulp Fiction","rating":8.3,"vote_count":8670,"genre":"Crime","$$hashKey":"object:89"},{"title":"The Godfather: Part II","rating":8.3,"vote_count":3418,"genre":"Crime","$$hashKey":"object:90"},{"title":"Once Upon a Time in America","rating":8.3,"vote_count":1104,"genre":"Crime","$$hashKey":"object:91"},{"title":"Leon: The Professional","rating":8.2,"vote_count":4293,"genre":"Crime","$$hashKey":"object:92"}]',
  },

  'RECOMMEND': {
    'Tales of Terror': [13581, 9707, 13122, 13436, 37527],
    'Sansho the Bailiff': [19404, 15387, 278, 238, 372058],
    'Shrek': [82702, 137106, 812, 40623, 11970],
  },

  'BEST_OF': {
    '1910': '[{"genre":"Animation","title":"Gertie the Dinosaur","vote_count":27,"release_year":1914,"$$hashKey":"object:20"},{"genre":"Comedy","title":"The Immigrant","vote_count":55,"release_year":1917,"$$hashKey":"object:21"},{"genre":"Drama","title":"The Birth of a Nation","vote_count":109,"release_year":1915,"$$hashKey":"object:22"},{"genre":"History","title":"The Birth of a Nation","vote_count":109,"release_year":1915,"$$hashKey":"object:23"},{"genre":"Horror","title":"Frankenstein","vote_count":34,"release_year":1910,"$$hashKey":"object:24"},{"genre":"Romance","title":"Broken Blossoms","vote_count":41,"release_year":1919,"$$hashKey":"object:25"},{"genre":"Science Fiction","title":"Frankenstein","vote_count":34,"release_year":1910,"$$hashKey":"object:26"},{"genre":"War","title":"The Birth of a Nation","vote_count":109,"release_year":1915,"$$hashKey":"object:27"}]',
    '1980': '[{"genre":"Action","title":"The Empire Strikes Back","vote_count":5998,"release_year":1980,"$$hashKey":"object:44"},{"genre":"Adventure","title":"Back to the Future","vote_count":6239,"release_year":1985,"$$hashKey":"object:45"},{"genre":"Animation","title":"The Little Mermaid","vote_count":1921,"release_year":1989,"$$hashKey":"object:46"},{"genre":"Comedy","title":"Back to the Future","vote_count":6239,"release_year":1985,"$$hashKey":"object:47"},{"genre":"Crime","title":"Scarface","vote_count":3017,"release_year":1983,"$$hashKey":"object:48"},{"genre":"Documentary","title":"Koyaanisqatsi","vote_count":140,"release_year":1982,"$$hashKey":"object:49"},{"genre":"Drama","title":"Blade Runner","vote_count":3833,"release_year":1982,"$$hashKey":"object:50"},{"genre":"Family","title":"Back to the Future","vote_count":6239,"release_year":1985,"$$hashKey":"object:51"},{"genre":"Fantasy","title":"E.T. the Extra-Terrestrial","vote_count":3359,"release_year":1982,"$$hashKey":"object:52"},{"genre":"Foreign","title":"Howling III: The Marsupials","vote_count":30,"release_year":1987,"$$hashKey":"object:53"},{"genre":"History","title":"The Untouchables","vote_count":1424,"release_year":1987,"$$hashKey":"object:54"},{"genre":"Horror","title":"The Shining","vote_count":3890,"release_year":1980,"$$hashKey":"object:55"},{"genre":"Music","title":"Dirty Dancing","vote_count":1371,"release_year":1987,"$$hashKey":"object:56"},{"genre":"Mystery","title":"The Thing","vote_count":1629,"release_year":1982,"$$hashKey":"object:57"},{"genre":"Romance","title":"Top Gun","vote_count":1736,"release_year":1986,"$$hashKey":"object:58"},{"genre":"Science Fiction","title":"Back to the Future","vote_count":6239,"release_year":1985,"$$hashKey":"object:59"},{"genre":"Thriller","title":"The Terminator","vote_count":4208,"release_year":1984,"$$hashKey":"object:60"},{"genre":"TV Movie","title":"The Day After","vote_count":97,"release_year":1983,"$$hashKey":"object:61"},{"genre":"War","title":"Full Metal Jacket","vote_count":2595,"release_year":1987,"$$hashKey":"object:62"},{"genre":"Western","title":"¡Three Amigos!","vote_count":287,"release_year":1986,"$$hashKey":"object:63"}]'
  },

}
